version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: infra/Dockerfile.server
    container_name: project-manager-backend
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - JWT__Key=${JWT_KEY:-your-development-secret-key-must-be-at-least-32-chars-long}
      - ConnectionStrings__Default=Data Source=/data/projectmanager.db
    volumes:
      - db-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: infra/Dockerfile.web
      args:
        - VITE_API_BASE_URL=http://localhost:5000
    container_name: project-manager-frontend
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db-data:
    driver: local

networks:
  default:
    name: project-manager-network
